version: "3.9"

services:
  neo4j:
    environment:
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=localhost
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_http_enabled=true
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_http_advertised__address=:7474
      - NEO4J_dbms_windows__service__name=neo4j
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=512m
      - NEO4J_dbms_security_procedures_unrestricted=spatial.*
      - NEO4J_dbms_databases_default__to__read__only=false
      - NEO4J_dbms_databases_writable=true
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-123456}
      
    build: 
      dockerfile: neo4j-dockerfile  
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - "./neo4j/data:/data"
      - "./neo4j/logs:/logs"

  python:
    environment:
      - NEO4J_HOST=${NEO4J_HOST:-localhost}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-123456}
      - CROSS_SERVER_SECRET=${SECRET:-supersecret}
    build:
      dockerfile: python-dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "neo4j"
    command: python agrograph-api/manage.py runserver 0.0.0.0:8000
networks:
  default:
    driver: bridge
    